# Storage configuration
storage: /verdaccio/storage/data
plugins: /verdaccio/plugins

# Listen on all interfaces
listen: 0.0.0.0:4873

# Package storage configuration
packages:
  '@my-comp/*':
    # Allow all authenticated users to read (install) the package
    access: $all
    # Allow both ci-user and admin to publish
    publish: ci-user admin
    # Disable proxying to external registries
    proxy: none

  '@mycompany/*':
    # Allow all authenticated users to read (install) the package
    access: $all
    # Allow both ci-user and admin to publish
    publish: ci-user admin
    # Disable proxying to external registries
    proxy: none

  '**':
    # Allow authenticated users to read any package
    access: $all
    # Allow both ci-user and admin to publish any package
    publish: ci-user admin
    # Disable proxying to external registries
    proxy: none

# Authentication
auth:
  htpasswd:
    file: /verdaccio/conf/htpasswd
    # Disable user registration (only admins can create accounts)
    max_users: -1

# Server settings
server:
  keepAliveTimeout: 60

# Security settings
security:
  api:
    jwt:
      enabled: true
      secret: ${JWT_SECRET}
  web:
    enable: true
    title: MyComp Private NPM Registry

# Uplinks (disable external registries)
uplinks: {}

# Logging configuration for audit logs
logs:
  - { type: stdout, format: pretty, level: info }
  - { type: file, path: /verdaccio/storage/audit.log, level: info }

# HTTP configuration (HTTPS disabled for initial setup)
# To enable HTTPS later, uncomment the https section and add certificates

# Middleware for audit logging
middlewares:
  audit:
    enabled: true